### PR TITLE
Add kor/dev-3.md

### PR DESCRIPTION
**Pull request by ppapman1**
I added `dev-3.md` to the Korean Modding Guide. This document covers mod uploads.

### CODE REVIEW

**Review by CrackThrough — CHANGES_REQUESTED** [review]
We should not use the "same" image with a different name like `image1` and `image2`.

Instead, you can put a directory separately inside a `resources/dev3` folder with `eng/` and `kor/` and use the name `image1`.

Please commit a fix and I will merge your pull request.

**Comment by CrackThrough** [comment]
I appreciate your contribution! But you need to fix few things first in order for me to merge your pull request. I left comments on few things I want them to be fixed first, and then I will merge your pull request.

**Comment by ppapman1** [comment]
Okay. I fixed it.

**Comment by CrackThrough** [comment]
Thanks for contributing!

**Pull request merged**
